### ISSUE TITLE
Feature requests (improvements, remember window position and mode, etc.)

### ISSUE THREAD

**Issue by Senorsen** [xzh1206/Ikas#1]
Nice job! Thank you for your nice work!

I think if the features below can be finished, the software would be better:
1. Remember the last window position.
2. Remember the last mode.
3. Pull last matches information periodically,  so there will no blank window when hovering on the level text.  ![image](https://user-images.githubusercontent.com/4176091/60282678-1a4e4200-993a-11e9-9fac-053d917c0560.png)
4. Add some seconds hover out timeout for float windows.
5. Use mouse 'pointer' to indicate where is a button.
6. Rank 'S+' is very ambiguous, it should be an exact rank level (like S+5).

**Comment by zhxie** [comment]
Thank you for your suggestion, and I will take them into consideration.
As for the third one, Ikas now pulls battle data every a few seconds, but will only render the data when the battle window is visible. Before Ikas renders the data, it will try to check battles again for timeliness. As a result, I may add some animation for loading next time : )
