### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by tkgstrator** [xzh1206/Ikas#2]
Environment
* Windows10
* Visual Studio 2019
* .NET Framework 4.7.2
* .NET Core 2.0

When VS2019 load IkasLib.csproj, `The SDK 'Microsoft.NET.Sdk' specified could not be found`.
How to fix it?

**Comment by zhxie** [comment]
I didn't encounter this problem, but my .NET Core SDK version is 2.1.701(which was installed by Visual Studio 2019), I guess updating the SDK may solve this problem.

And I also searched for related issues, if this problem still exists, may be the environment variable `MSBuildSDKsPath` points to the wrong SDK.
